### ISSUE TITLE
[Confirmation] What is the behavior of simple searching?

### ISSUE THREAD

**Issue by ken-phung** [myapollorepo/sfa#24]
[Confirmation] What is the behavior of simple searching?
![6](https://user-images.githubusercontent.com/59155125/81542718-4f6f5180-939f-11ea-8df5-c8b692d1c231.png)

How about space in keyword "geo region"? treat it as 1 keyword?

**Comment by myapollorepo** [comment]
Depend on the searching mechanism, such like Google, space splits words, let’s start as simple as relative search <field> like N’%<key word>%’
